pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Clean workspace and checkout code from the specified branch
                cleanWs()
                checkout([$class: 'GitSCM', branches: [[name: '*/develop']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/akhileshranjan2308/assignment1']]])
            }
        }

        stage('Build') {
            steps {
                // Add your build steps here if needed
                echo 'Building...'
            }
        }

        // Add more stages as needed

    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
    }
}
