pipeline {
    agent any

    stages {
        stage('Debug') {
            steps {
                script {
                    echo "Current directory: ${pwd()}"
                    echo "Workspace contents:"
                    sh "ls -la"
                }
            }
        }

        stage('Checkout') {
            steps {
                script {
                    // Check out code from the Develop branch
                    checkout([$class: 'GitSCM', branches: [[name: '*/develop']], userRemoteConfigs: [[url: 'https://github.com/akhileshranjan2308/assignment1']]])
                }
            }
        }

        // ... (other stages)
    }
}
