pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                script {
                    // Check out code from the Develop branch and specify the path to Jenkinsfile
                    checkout([$class: 'GitSCM', branches: [[name: '*/develop']], userRemoteConfigs: [[url: 'https://github.com/akhileshranjan2308/assignment1']]], scriptPath: 'Jenkinsfile')
                }
            }
        }

        // ... (other stages)
    }
}
